sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: e9R7JN3XOg1tF1dk4O9s9yu1ongtHq+VKmHHFXCDqYh88Rkvn1MPLU9XX0IjqC3IR7SJLgdzDuYz2DNgg9AxjyQX43zFvOmDatT9f5GNpvKW6Fh9AqH74ZyO8gTn+UFRd20YxDffM0kVcMBHM3xP+1eyXDSavEA+GGp6fuYu0IRRbQrKyC2gOTApJjZzVTbYA+lzp4hNXjVxUbzqM4rmuM2ILUqxQpDxzzPezn8GAeojZxz+OgdPPE89ioQOgz38kZxWpz8v7m7OFimAaH+koU2sP2S8eJjiuWU9gM6ptugtMLRi7ZNwbDiR1joMBRc3j2eoP1GVNiHPIhbjTofHqPSnfip/9HFWax0jHq4N8njJOSaaxxD/7Bqaus1zrlCcU4xP9VzL3QGxtR70VyhfS+DaHIMx8mPiipOZ0D3ElPGdhFW4w1vJzuJU2HcKi5q2jrzjWlldUYglaR393omlXJFXZO1/zQgjxpiXHX5pFUrujcIZE7cSdls/dwsuxgRWg81iPWcICRrUXiDlN+ifEUg0hpgi4sE54/aveyBKA+vP0LwGxT4tB4paCcxcqR61Xj1fZEVOVhP/jUbr2ATLw1MmORST1rtY6Jpx4YsV0JCGvHvN4oPkPOY1PoS+Iwer4HOzgXn68XAuXYyjJHBh1i2Nsy1213aHxD+kDeqS8G0=
  - secure: b/qbeXXUPVgmC0uy7cdSB3RcGwFYy5pRfEn6DWcfAQVrjPLzFdJJxTkn8oLtEnYaGsoQ/Hb2AiyS1Y+LoZJZ9fmzvtdzruJvQoWKhiBy6SJ70idVMDUwKwMMoZaOYY9/sh5v/3ZV/Xmjo2heOrmvJyioXx4WGQWRcmLYnNBAmcsyt17P/CmNCgqSxnJ99I3CO1IVAGq6DPs8Uu5A5n8vyFfyQRgDVIwHp8ws0jDaOb3OhjrM6GnPGhHtB5I8qQLohZ8/mNiUgiuhr/1FL9pN6AJc8jnIvbfmUQgHqTBHTnazxIPFp+67HP5juaB8dM/qeFG7+UVGMNwl+y9rt9FYD4V3QGg1Gyhoa66ef+n+26OBtyaWkdtB6NAZBcXxFFYQHEA8bvfjSOUSXHsDG3WMj81qhiFQ1FPyN0WqISOz/boDQ3RQ0MxtTlDjkfxNaBSqdfXuu3wqa0N7nTEx2ZipJS2Wgmij8o2vJ6zUI7yWbQ3IfvdkOZy0nctH4WnQxa1B52tgeV+wOJNqLJEzqeizIbwPktIF1MDTG61mRo+ykcAB3rY8Nc+se6YWSFAWO62B7uJ7e+qZUs6EmfhD/gFUEVJv+rhY0vDXADP1em9dkurHN5KZGygIQAIovgEVNHzaRCMHufjSIu0AfgkIYKzSP0qwRQibCSPcv1NuH2uCtaA=
